models/Model.py
from sqlalchemy import Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from application import config

engine = create_engine(config.ENGINE_STRING, echo=False)

Base = declarative_base()

Session = sessionmaker(bind=engine)
db_session = Session()

class User(Base):
    __tablename__ = 'users'

    user_id = Column(Integer, primary_key=True)
    first_name = Column(String)
    last_name = Column(String)
    password = Column(String)
    email = Column(String)
    phone = Column(String)
    location = Column(String)

app.py
from flask import Flask
import config

"""import all controller from application.controllers"""
from controllers.page import page
"""import more controller"""

app = Flask(__name__)
app.secret_key = config.SECRET_KEY

"""register each controller as blueprint"""
app.register_blueprint(page)
"""register more controller"""

if __name__ == '__main__':
    app.debug = True
    app.run(port=config.PORT)

controllers/page.py
from flask import Blueprint, render_template, abort
from flask import Flask, session, redirect, url_for, escape, request, flash, get_flashed_messages
from jinja2 import TemplateNotFound
from models import *

page = Blueprint('page', __name__, template_folder='application/templates')

@page.route('/index')
@page.route('/')
def index():
    try:
        return render_template('home.html')
    except TemplateNotFound:
        abort(404)

@page.route('/page', defaults={'page': 'index'})
@page.route('/page/<page>')
def show(page):
    try:
        return render_template('pages/%s.html' % page)
    except TemplateNotFound:
        abort(404)

templates/home.html
<h1>Home</h1>

templates/layout.html
<!DOCTYPE HTML>
<head>
    <title>Flask Starter Project</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>    
    <a style="text-align:center" href="{{ url_for('page.index') }}">Home</a>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

templates/pages/about.html
{% extends "layout.html" %}

{% block title %}About{% endblock %}

{% block head %}
  {{ super() }}
  <style type="text/css">
    .important { color: #336699; }
  </style>
{% endblock %}

{% block content %}
  <h1>About</h1>
  <p class="important">Lorem ipsum.</p>
{% endblock %}

templates/pages/index.html
{% extends "layout.html" %}

{% block title %}Index{% endblock %}

{% block head %}
  {{ super() }}
  <style type="text/css">
    .important { color: #336699; }
  </style>
{% endblock %}

{% block content %}
  <h1>Index</h1>
  <p class="important">Hello.</p>
{% endblock %}